name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
        env:
          CI: true
      - uses: actions/upload-artifact@master
        with:
          name: hristov.dev
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - uses: actions/download-artifact@master
        with:
          name: hristov.dev
          path: .
        
      - name: rsync deployments
        uses: contention/rsync-deployments@v1.0.0
        with:
          secrets: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-avzr --delete ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_DIR }}"
