name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
        env:
          CI: true
      
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "dist/*"
          target: ${{ secrets.SSH_REMOTE_DIR }}

      - uses: actions/upload-artifact@master
        with:
          name: hristov.dev
          path: dist
